def archiveName = "vosk-android"
def pomName = "Vosk Android"
def pomDescription = "Vosk speech recognition library for Android"

apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'

android {
    namespace 'org.vosk'
    compileSdkVersion 36
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 10
        versionName = version
        archivesBaseName = archiveName
        ndkVersion = "28.2.13676358"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

task buildVosk(type: Exec) {
    commandLine './build-vosk.sh'
    environment ANDROID_NDK_HOME: android.getNdkDirectory()
}

dependencies {
    api 'net.java.dev.jna:jna:5.13.0@aar'
    implementation platform('com.google.firebase:firebase-bom:33.5.1')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-perf'
    implementation 'com.google.firebase:firebase-config'
}

//preBuild.dependsOn buildVosk

mavenPublishing {
    coordinates("com.alphacephei", archiveName, version)
    pom {
        name = pomName
        description = pomDescription
    }
}
